

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

//LOGIN USERS ACTIONS
export const LOGOUT = 'LOGOUT';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const UPDATE_STATE_VALIDATION_ERROR = 'UPDATE_STATE_VALIDATION_ERROR';

//REIMBURSEMENTS ACTIONS
export const GET_REIMBURSEMENTS_BY_ID = 'GET_REIMBURSEMENTS_BY_ID';
export const GET_REIMBURSEMENTS_BY_ID_SUCCESS = 'GET_REIMBURSEMENTS_BY_ID_SUCCESS';

export const ADD_REIMBURSEMENT = 'ADD_REIMBURSEMENT';
export const ADD_REIMBURSEMENT_SUCCESS = 'ADD_REIMBURSEMENT_SUCCESS';

//USERS LIST ACTIONS
export const GET_LIST_USERS = 'GET_LIST_USERS'
export const GET_LIST_USERS_SUCCESS = 'GET_LIST_USERS_SUCCESS'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

//message actions
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

